version: '3'
services:
  firefox:
    image: jlesage/firefox
    restart: always
    ports:
      - "5800:5800"
    volumes:
      - "./config:/config:rw"
    environment:
      FF_PREF_FIRSTLAUNCH_REDDIT: startup.homepage_welcome_url="https://new.reddit.com/r/place/#" #Open the canvas on first launch.
      FF_PREF_USERSCRIPT_DOWNLOAD: startup.homepage_welcome_url.additional="data:text/html,<script>setTimeout(()=>window.location='https://github.com/PlaceNL/Userscript/releases/download/latest/placenl-userscript-autoupdater.user.js',5000)</script>" #On first launch, wait a bit for tampermonkey to be installed, then open the PlaceNL script. This should popup a tab with the install button.
      FF_PREF_REDDIT: browser.startup.homepage="https://new.reddit.com/r/place/#" #Also open the canvas on every other launch.
      FF_PREF_FORCE_EXTENSION: extensions.autoDisableScopes=14 #without this, tampermonkey gets ignored.
      FF_PREF_DISABLE_RESTORE_SESSION: browser.sessionstore.resume_from_crash=false #Disable "restore session" stuff.
      TZ: CET #Change timezone to Dutch time. This should fix the 2 hour offset with the "Placing next pixel at" message